### ISSUE TITLE
npm build "node esbuild.config.js"

### ISSUE THREAD

**Issue by MCarroll** [marcoroth/rails7-stimulus-reflex-esbuild#8]
`npm set-script build "node esbuild.config.js"`

```
❯ npm set-script build "node esbuild.config.js"
npm WARN set-script set-script is deprecated, use `npm pkg set scripts.scriptname="cmd" instead.
npm ERR! package.json not found
```

`yarn build` works. 

https://esbuild.github.io/getting-started/#your-first-bundle

`❯ yarn build
yarn run v1.22.19
$ node esbuild.config.js
✨  Done in 0.57s.`

**Comment by marcoroth** [comment]
Hey @MCarroll

If you have a new app the `yarn build` command won't be present. By running the `npm set-script ...` command it will setup the `yarn build` command so that you can later run it.

Technically this step is optional if you already have a build command setup.
